python3 train.py \
    "/media/patrick/New Volume/chess_project/data.binpack" \
    "/media/patrick/New Volume/chess_project/data.binpack" \
    --gpus "0," \
    --depth-list 128,128,128 \
    --dff-list 128,128 \
    --num-heads 16 \
    --threads 6 \
    --num-workers 4 \
    --batch-size 128 \
    --random-fen-skipping 16 \
    --features Transformer \
    --lr 0.00009 \
    --lambda 1.0 \
    --gamma 0.998 \
    --validation-size 8192 \
    --max_epochs 4000 \
    --smolgen-initial 64 \
    --smolgen-hidden 64 \
    --eval-hidden-depth 128 \
    --activation-function relu \
    --policy-classification-weight 0.000002 \
    --return-policy-index yes \
    --epoch-size 8192000 \
    --default_root_dir ./training/runs/transformer \
